flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://www.github.com/mattjbray/elm-export
    commit: 3dfafc7a717003ff4374119ff6f60e5b56868d8f
  extra-dep: true
- location:
    git: https://www.github.com/mattjbray/servant-elm
    commit: 36c90557d17d237e621cdcb4912ae9e4f25a9e59
  extra-dep: true
extra-deps:
- aeson-0.11.2.1
- base-compat-0.9.1
- base-orphans-0.5.4
- bytestring-builder-0.10.8.1.0
- conduit-extra-1.1.13.2
- datetime-0.3.1
- fast-logger-2.4.6
- http2-1.1.0
- opaleye-0.5.1.1
- postgresql-libpq-0.9.2.0
- postgresql-simple-0.5.2.1
- servant-0.5
- servant-foreign-0.5
- servant-server-0.5
- unix-time-0.3.7
- wai-3.0.3.0
- wai-extra-3.0.17
- wai-logger-2.3.0
- warp-3.1.3.1
resolver: lts-5.10
