flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- bytestring-builder-0.10.8.1.0
- datetime-0.3.1
- fast-logger-2.4.7
- http-api-data-0.3.1
- opaleye-0.5.1.1
- postgresql-libpq-0.9.2.0
- servant-0.9
- servant-server-0.9
- unix-time-0.3.7
- wai-extra-3.0.18
resolver: lts-6.12
